spring:
  application:
    name: devices_rag_app
  data:
    mongodb:
      uri: mongodb+srv://atw:atw@ai-cluster.osbvqyw.mongodb.net/?appName=ai-cluster
      database: devices
  ai:
    vectorstore:
      mongodb:
        initialize-schema: true
    #OpenAI - Configuration
    #openai:
      #api-key: {OPENAI_API_KEY}
      #chat:
        #options:
          #model: gpt-3.5-turbo
    #Embeddings
    model:
      embedding: ollama
   # Ollama - Configuration
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: gemma3:latest
          temperature: 0.7
      embedding:
        options:
          model: nomic-embed-text